# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'
variables:
  buildConfiguration: 'Release'
steps:
- task: NuGetToolInstaller@0
  displayName: "NuGet use 4.6.2"
  inputs:
      versionSpec: 4.6.2
- task: DotNetCoreCLI@2
displayName: Restore Packages
inputs:
    command: restore
    feedsToUse: config
    nugetConfigPath: 'nuget.config'
    projects: $(buildProjects)
    noCache: true
    verbosityRestore: Normal
- task: DotNetCoreCLI@2
  displayName: ".NET build"
  inputs:
      projects: '**/*.csproj'
      arguments: --configuration $(BuildConfiguration) --no-restore
- task: DotNetCoreCLI@2
  displayName: ".NET test"
  inputs:
      command: test
      projects: 'test\**.csproj'