# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: "NuGet use 4.6.2"
  inputs:
      versionSpec: 4.6.2

- task: DotNetCoreCLI@2
  displayName: ".NET build Client"
  inputs:
      command: build
      projects: '**/PinterestService.Client.csproj'
      arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)

- task: DotNetCoreCLI@2
  displayName: ".NET build Test Project"
  inputs:
      command: build
      projects: '**/PinterestService.Tests.csproj'
      arguments: --configuration $(BuildConfiguration)

- task: DotNetCoreCLI@2
  displayName: ".NET test"
  inputs:
      command: test
      projects: '**/*Tests.csproj'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: deploy
    artifactType: container