# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'
variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'
steps:

- task: NuGetToolInstaller@0
  displayName: "NuGet use 4.6.2"
  inputs:
      versionSpec: 4.6.2

- task: DotNetCoreCLI@2
  displayName: ".NET build"
  inputs:
      projects: '**/*.csproj'
      arguments: --configuration $(BuildConfiguration)

- task: DotNetCoreCLI@2
  displayName: ".NET test"
  inputs:
      command: test
      projects: '**/*Tests.csproj'